version: "3"

services:
  taste-test-viewer:
    container_name: taste-test-viewer
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - postgres

networks:
  postgres:
    external:
      name: postgres-network
